//
//  TestCases.swift
//  ATSyntaxTools
//
//  Created by Christopher Jr Riley on 2026-07-01.
//


public enum TestCases {
    public static let validHandles = [
        "A.ISI.EDU",
        "XX.LCS.MIT.EDU",
        "SRI-NIC.ARPA",
        "john.test",
        "jan.test",
        "a234567890123456789.test",
        "john2.test",
        "john-john.test",
        "john.bsky.app",
        "jo.hn",
        "a.co",
        "a.org",
        "joh.n",
        "j0.h0",
        "jaymome-johnber123456.test",
        "jay.mome-johnber123456.test",
        "john.test.bsky.app",
        "shoooort" + String(repeating: ".loooooooooooooooooooooooooong", count: 8) + ".test",
        "short." + String(repeating: "o", count: 63) + ".test",
        "john.t",
        "laptop.local",
        "laptop.arpa",
        "xn--ls8h.test",
        "xn--bcher-kva.tld",
        "xn--3jk.com",
        "xn--w3d.com",
        "xn--vqb.com",
        "xn--ppd.com",
        "xn--cs9a.com",
        "xn--8r9a.com",
        "xn--cfd.com",
        "xn--5jk.com",
        "xn--2lb.com",
        "expyuzz4wqqyqhjn.onion",
        "friend.expyuzz4wqqyqhjn.onion",
        "g2zyxa5ihm7nsggfxnu52rck2vv4rvmdlkiu3zzui5du4xyclen53wid.onion",
        "friend.g2zyxa5ihm7nsggfxnu52rck2vv4rvmdlkiu3zzui5du4xyclen53wid.onion",
        "2gzyxa5ihm7nsggfxnu52rck2vv4rvmdlkiu3zzui5du4xyclen53wid.onion",
        "friend.2gzyxa5ihm7nsggfxnu52rck2vv4rvmdlkiu3zzui5du4xyclen53wid.onion",
        "12345.test",
        "8.cn",
        "4chan.org",
        "4chan.o-g",
        "blah.4chan.org",
        "thing.a01",
        "120.0.0.1.com",
        "0john.test",
        "9sta--ck.com",
        "99stack.com",
        "0ohn.test",
        "john.t--t",
        "thing.0aa.thing",
        "stack.com",
        "sta-ck.com",
        "sta---ck.com",
        "sta--ck9.com",
        "stack99.com",
        "sta99ck.com",
        "google.com.uk",
        "google.co.in",
        "google.com",
        "maselkowski.pl",
        "m.maselkowski.pl",
        "xn--masekowski-d0b.pl",
        "xn--fiqa61au8b7zsevnm8ak20mc4a87e.xn--fiqs8s",
        "xn--stackoverflow.com",
        "stackoverflow.xn--com",
        "stackoverflow.co.uk"
    ]

    public static let invalidHandles = [
        "did:thing.test",
        "did:thing",
        "john-.test",
        "john.0",
        "john.-",
        "xn--bcher-.tld",
        "john..test",
        "jo_hn.test",
        "-john.test",
        ".john.test",
        "jo!hn.test",
        "jo%hn.test",
        "jo&hn.test",
        "jo@hn.test",
        "jo*hn.test",
        "jo|hn.test",
        "jo:hn.test",
        "jo/hn.test",
        "john💩.test",
        "bücher.test",
        "john .test",
        "john.test.",
        "john",
        "john.",
        ".john",
        " john.test",
        "john.test ",
        "joh-.test",
        "john.-est",
        "john.tes-",
        "shoooort" + String(repeating: ".loooooooooooooooooooooooooong", count: 9) + ".test",
        "short." + String(repeating: "o", count: 64) + ".test",
        "org",
        "ai",
        "gg",
        "io",
        "cn.8",
        "thing.0aa",
        "127.0.0.1",
        "192.168.0.142",
        "fe80::7325:8a97:c100:94b",
        "2600:3c03::f03c:9100:feb0:af1f",
        "-notvalid.at-all",
        "-thing.com",
        "www.masełkowski.pl.com"
    ]

    public static let validDIDs = [
        "did:method:val",
        "did:method:VAL",
        "did:method:val123",
        "did:method:123",
        "did:method:val-two",
        "did:method:val_two",
        "did:method:val.two",
        "did:method:val:two",
        "did:method:val%BB",
        "did:method:" + String(repeating: "v", count: 240),
        "did:m:v",
        "did:method::::val",
        "did:method:-",
        "did:method:-:_:.:%ab",
        "did:method:.",
        "did:method:_",
        "did:method::.",
        "did:onion:2gzyxa5ihm7nsggfxnu52rck2vv4rvmdlkiu3zzui5du4xyclen53wid",
        "did:example:123456789abcdefghi",
        "did:plc:7iza6de2dwap2sbkpav7c6c6",
        "did:web:example.com",
        "did:web:localhost%3A1234",
        "did:key:zQ3shZc2QzApp2oymGvQbzP8eKheVshBHbU4ZYjeXqwSKEn6N",
        "did:ethr:0xb9c5714089478a327f09197987f16f9e5d936e8a"
    ]

    public static let invalidDIDs = [
        "did",
        "didmethodval",
        "method:did:val",
        "did:method:",
        "didmethod:val",
        "did:methodval)",
        ":did:method:val",
        "did.method.val",
        "did:method:val:",
        "did:method:val%",
        "DID:method:val",
        "did:METHOD:val",
        "did:m123:val",
        "did:method:val/two",
        "did:method:val?two",
        "did:method:val#two",
        "did:method:" + String(repeating: "v", count: 2_049)
    ]

    public static let validNSIDs = [
        "com." + String(repeating: "o", count: 63) + ".foo",
        "com.example." + String(repeating: "o", count: 63),
        "com." + String(repeating: "middle.", count: 40) + "foo",
        "com.example.fooBar",
        "com.example.fooBarV2",
        "net.users.bob.ping",
        "a.b.c",
        "m.xn--masekowski-d0b.pl",
        "one.two.three",
        "one.two.three.four-and.FiVe",
        "one.2.three",
        "a-0.b-1.c",
        "a0.b1.cc",
        "cn.8.lex.stuff",
        "test.12345.record",
        "a01.thing.record",
        "a.0.c",
        "xn--fiqs8s.xn--fiqa61au8b7zsevnm8ak20mc4a87e.record.two",
        "a0.b1.c3",
        "com.example.f00",
        "onion.expyuzz4wqqyqhjn.spec.getThing",
        "onion.g2zyxa5ihm7nsggfxnu52rck2vv4rvmdlkiu3zzui5du4xyclen53wid.lex.deleteThing",
        "org.4chan.lex.getThing",
        "onion.2gzyxa5ihm7nsggfxnu52rck2vv4rvmdlkiu3zzui5du4xyclen53wid.lex.deleteThing"
    ]

    public static let invalidNSIDs = [
        "com." + String(repeating: "o", count: 64) + ".foo",
        "com.example." + String(repeating: "o", count: 64),
        "com." + String(repeating: "middle.", count: 50) + "foo",
        "com.example.foo.*",
        "com.example.foo.blah*",
        "com.example.foo.*blah",
        "com.exa💩ple.thing",
        "a-0.b-1.c-3",
        "a-0.b-1.c-o",
        "1.0.0.127.record",
        "0two.example.foo",
        "example.com",
        "com.example",
        "a.",
        ".one.two.three",
        "one.two.three ",
        "one.two..three",
        "one .two.three",
        " one.two.three",
        "com.atproto.feed.p@st",
        "com.atproto.feed.p_st",
        "com.atproto.feed.p*st",
        "com.atproto.feed.po#t",
        "com.atproto.feed.p!ot",
        "com.example-.foo",
        "com.example.fooBar.2"
    ]

    public static let validRecordKeys = [
        "self",
        "example.com",
        "~1.2-3_",
        "dHJ1ZQ",
        "_",
        "literal:self",
        "pre:fix",
        ":",
        "-",
        "~",
        "...",
        "self.",
        "lang:",
        ":lang",
        String(repeating: "o", count: 512)
    ]

    public static let invalidRecordKeys = [
        "alpha/beta",
        ".",
        "..",
        "@handle",
        "a" + "ny space",
        "a" + "ny+space",
        "number[3]",
        "number(3)",
        "\"quote\"",
        "dHJ1ZQ==",
        String(repeating: "o", count: 513)
    ]

    public static let validTIDs = [
        "3jzfcijpj2z2a",
        "7777777777777",
        "3zzzzzzzzzzzz",
        "2222222222222"
    ]

    public static let invalidTIDs = [
        "3jzfcijpj2z21",
        "0000000000000",
        "3JZFCIJPJ2Z2A",
        "3jzfcijpj2z2aa",
        "3jzfcijpj2z2",
        "222",
        "3jzf-cij-pj2z-2a",
        "zzzzzzzzzzzzz",
        "kjzfcijpj2z2a"
    ]

    public static let validATURIs = [
        "at://did:plc:asdf123",
        "at://user.bsky.social",
        "at://did:plc:asdf123/com.atproto.feed.post",
        "at://did:plc:asdf123/com.atproto.feed.post/record",
        "at://did:plc:asdf123/com.atproto.feed.post/" + String(repeating: "o", count: 512),
        "at://did:plc:asdf123/com.atproto.feed.post/asdf123",
        "at://did:plc:asdf123/com.atproto.feed.post/a",
        "at://did:plc:asdf123/com.atproto.feed.post/asdf-123",
        "at://did:abc:123",
        "at://did:abc:123/io.nsid.someFunc/record-key",
        "at://did:abc:123/io.nsid.someFunc/self.",
        "at://did:abc:123/io.nsid.someFunc/lang:",
        "at://did:abc:123/io.nsid.someFunc/:",
        "at://did:abc:123/io.nsid.someFunc/-",
        "at://did:abc:123/io.nsid.someFunc/_",
        "at://did:abc:123/io.nsid.someFunc/~",
        "at://did:abc:123/io.nsid.someFunc/...",
        "at://did:plc:asdf123/com.atproto.feed.postV2",
        "at://did:web:x" + String(repeating: ".y", count: 100) + "/com.atproto.feed.post/record"
    ]

    public static let invalidATURIs = [
        "a://did:plc:asdf123",
        "at//did:plc:asdf123",
        "at:/a/did:plc:asdf123",
        "at:/did:plc:asdf123",
        "AT://did:plc:asdf123",
        "http://did:plc:asdf123",
        "://did:plc:asdf123",
        "at:did:plc:asdf123",
        "at:///did:plc:asdf123",
        "at://:/did:plc:asdf123",
        "at:/ /did:plc:asdf123",
        "at://did:plc:asdf123 ",
        "at://did:plc:asdf123/ ",
        " at://did:plc:asdf123",
        "at://did:plc:asdf123/com.atproto.feed.post ",
        "at://did:plc:asdf123/com.atproto.feed.post# ",
        "at://did:plc:asdf123/com.atproto.feed.post#/ ",
        "at://did:plc:asdf123/com.atproto.feed.post#/frag ",
        "at://did:plc:asdf123/com.atproto.feed.post#fr ag",
        "//did:plc:asdf123",
        "at://name",
        "at://name.0",
        "at://diD:plc:asdf123",
        "at://did:plc:asdf123/com.atproto.feed.p@st",
        "at://did:plc:asdf123/com.atproto.feed.p$st",
        "at://did:plc:asdf123/com.atproto.feed.p%st",
        "at://did:plc:asdf123/com.atproto.feed.p&st",
        "at://did:plc:asdf123/com.atproto.feed.p()t",
        "at://did:plc:asdf123/com.atproto.feed_post",
        "at://did:plc:asdf123/-com.atproto.feed.post",
        "at://did:plc:asdf@123/com.atproto.feed.post",
        "at://did:plc:asdf123?a",
        "at://user.bsky.social?a=B",
        "at://did:plc:asdf123/com.atproto.feed.post?foo=bar",
        "at://did:plc:asdf123/com.atproto.feed.post/record?q=3",
        "at://DID:plc:asdf123",
        "at://user.bsky.123",
        "at://bsky",
        "at://did:plc:",
        "at://frag",
        "at://did:plc:asdf123/com.atproto.feed.post/" + String(repeating: "o", count: 513),
        "at://did:plc:" + String(repeating: "o", count: 8_200) + "/com.atproto.feed.post/record",
        "at://user.bsky.social//",
        "at://user.bsky.social//com.atproto.feed.post",
        "at://user.bsky.social/com.atproto.feed.post//",
        "at://did:plc:asdf123/com.atproto.feed.post/asdf123/more/more",
        "at://did:plc:asdf123/short/stuff",
        "at://did:plc:asdf123/12345",
        "at://did:plc:asdf123/",
        "at://user.bsky.social/",
        "at://did:plc:asdf123/com.atproto.feed.post/",
        "at://did:plc:asdf123/com.atproto.feed.post/record/",
        "at://did:plc:asdf123/com.atproto.feed.post/record/#/frag",
        "at://did:plc:asdf123#",
        "at://did:plc:asdf123##",
        "at://did:plc:asdf123#/asdf#/asdf",
        "at://did:plc:asdf123#/frag",
        "at://did:plc:asdf123/com.atproto.feed.post/%23",
        "at://did:plc:asdf123/com.atproto.feed.post/$",
        "at://did:plc:asdf123/com.atproto.feed.post/@",
        "at://did:plc:asdf123/com.atproto.feed.post/!",
        "at://did:plc:asdf123/com.atproto.feed.post/*",
        "at://did:plc:asdf123/com.atproto.feed.post/(",
        "at://did:plc:asdf123/com.atproto.feed.post/,",
        "at://did:plc:asdf123/com.atproto.feed.post/;",
        "at://did:plc:asdf123/com.atproto.feed.post/abc%30123",
        "at://did:plc:asdf123/com.atproto.feed.post/%30",
        "at://did:plc:asdf123/com.atproto.feed.post/%3",
        "at://did:plc:asdf123/com.atproto.feed.post/%",
        "at://did:plc:asdf123/com.atproto.feed.post/%zz",
        "at://did:plc:asdf123/com.atproto.feed.post/%%%",
        "at://did:plc:asdf123/com.atproto.feed.post/.",
        "at://did:plc:asdf123/com.atproto.feed.post/.."
    ]
}
